#! /bin/bash

cd $(dirname $0)
source  $(dirname $0)/profile

while read -r line ; do
  case $line in
	C*)
      # Conky
      conky_infos="%{F#a1b56c}${line#?}%{F-}"
      ;;
    S*)
      # Clock and wifi
      sys_infos="${line#?}"
      ;;
	M*)
      # Music
      mus_infos="${line#?}"
      ;;
    W*)
      wm_infos=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          [OFU]*)
            # active desktop
            wm_infos="$wm_infos%{F$GREEN}%{R} ${name} %{R}%{F-}"
            ;;
          o*)
            # inactive but occupied desktop
            wm_infos="$wm_infos%{A:bspc desktop -f ${name}:} ${name} %{A}"
            ;;
          f*)
            # inactive desktop
			wm_infos="$wm_infos%{F#585858}%{A:bspc desktop -f ${name}:} ${name} %{A}%{F-}"
            ;;
          u*)
            # urgent desktop
            wm_infos="$wm_infos%{F$RED} %{A:bspc desktop -f ${name}:} ${name} %{A} %{F-}"
            ;;
          L*)
            # layout
            # layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
            wm_infos="$wm_infos $layout"
            ;;
        esac
        shift
      done
      ;;
  esac
  printf "%s\n" "%{l}$wm_infos%{c}$mus_infos%{r}$conky_infos  $sys_infos"
done
