#!/bin/sh
source $(dirname $0)/panel_config

mkfifo /tmp/fifo

bspc control --subscribe > /tmp/fifo &
clock -sf 'C%A %d %b %H:%M' > /tmp/fifo &

$(dirname $0)/bar.sh < /tmp/fifo | lemonbar -p -f $FONT1 -f $FONT2 -B "$DARK_GRAY" | sh
